name: CI - PR in Main Branch

on:
  pull_request:
    branches: [main]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Check End To End TEST
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: yarn e2e:headless
